import os
import os.path as osp
import random
import re
import subprocess
import time
from functools import partial
from typing import Any, Dict, List, Tuple

import mmengine
import yaml
from mmengine.config import ConfigDict
from mmengine.utils import track_parallel_progress

from opencompass.registry import RUNNERS, TASKS
from opencompass.utils import get_logger

from .base import BaseRunner


@RUNNERS.register_module()
class VOLCRunner(BaseRunner):
    """Distributed runner based on Volcano Cloud Cluster (VCC). It will launch
    multiple tasks in parallel with the 'vcc' command. Please install and
    configure VCC first before using this runner.

    Args:
        task (ConfigDict): Task type config.
        volcano_cfg (ConfigDict): Volcano Cloud config.
        max_num_workers (int): Max number of workers. Default: 32.
        retry (int): Number of retries when job failed. Default: 2.
        debug (bool): Whether to run in debug mode. Default: False.
        lark_bot_url (str): Lark bot url. Default: None.
    """

    def __init__(self,
                 task: ConfigDict,
                 volcano_cfg: ConfigDict,
                 queue_name: str,
                 max_num_workers: int = 32,
                 retry: int = 2,
                 debug: bool = False,
                 lark_bot_url: str = None):
        super().__init__(task=task, debug=debug, lark_bot_url=lark_bot_url)
        self.volcano_cfg = volcano_cfg
        self.max_num_workers = max_num_workers
        self.retry = retry
        self.queue_name = queue_name

    def launch(self, tasks: List[Dict[str, Any]]) -> List[Tuple[str, int]]:
        """Launch multiple tasks.

        Args:
            tasks (list[dict]): A list of task configs, usually generated by
                Partitioner.

        Returns:
            list[tuple[str, int]]: A list of (task name, exit code).
        """

        if not self.debug:
            status = track_parallel_progress(self._launch,
                                             tasks,
                                             nproc=self.max_num_workers,
                                             keep_order=False)
        else:
            status = [self._launch(task, random_sleep=False) for task in tasks]
        return status

    def _launch(self, task_cfg: ConfigDict, random_sleep: bool = True):
        """Launch a single task.

        Args:
            task_cfg (ConfigDict): Task config.
            random_sleep (bool): Whether to sleep for a random time before
                running the command. This avoids cluster error when launching
                multiple tasks at the same time. Default: True.

        Returns:
            tuple[str, int]: Task name and exit code.
        """

        task_type = self.task_cfg.type
        if isinstance(self.task_cfg.type, str):
            task_type = TASKS.get(task_type)
        task = task_type(task_cfg)
        num_gpus = task.num_gpus
        task_name = task.name
        # Build up VCC command
        pwd = os.getcwd()

        # Dump task config to file
        mmengine.mkdir_or_exist('tmp/')
        param_file = f'{pwd}/tmp/{os.getpid()}_params.py'
        task_cfg.dump(param_file)
        volc_cfg_file = f'{pwd}/tmp/{os.getpid()}_cfg.yaml'
        volc_cfg = self._choose_flavor(num_gpus)
        with open(volc_cfg_file, 'w') as fp:
            yaml.dump(volc_cfg, fp, sort_keys=False)

        shell_cmd = (
            f'source {self.volcano_cfg["bashrc_path"]}; '
            f'source {self.volcano_cfg["conda_env_name"]}; '
            # f'source {self.volcano_cfg["conda_path"]}; '
            # f'conda activate {self.volcano_cfg["conda_env_name"]}; '
            f'cd {pwd}; '
            '{task_cmd}')

        task_name = task_name[:128].replace('[', '-').replace(']', '').replace(
            '/', '-').replace(',', '--').replace('.', '_')
        tmpl = ('volc ml_task submit'
                f" --conf '{volc_cfg_file}'"
                f" --entrypoint '{shell_cmd}'"
                f' --task_name {task_name}'
                f' --resource_queue_name {self.queue_name}')
        get_cmd = partial(task.get_command, cfg_path=param_file, template=tmpl)
        cmd = get_cmd()

        logger = get_logger()
        logger.debug(f'Running command: {cmd}')

        out_path = task.get_log_path(file_extension='txt')
        mmengine.mkdir_or_exist(osp.split(out_path)[0])

        retry = self.retry
        while True:
            if random_sleep:
                time.sleep(random.randint(0, 10))
            task_status, returncode = self._run_task(cmd,
                                                     out_path,
                                                     poll_interval=20)
            output_paths = task.get_output_paths()
            if not (self._job_failed(task_status, output_paths)) \
                    or retry <= 0:
                break
            retry -= 1

        # Clean up
        os.remove(param_file)
        os.remove(volc_cfg_file)
        return task_name, returncode

    def _run_task(self, cmd, log_path, poll_interval):
        result = subprocess.run(cmd,
                                shell=True,
                                text=True,
                                capture_output=True)
        pattern = r'(?<=task_id=).*(?=\n\n)'
        match = re.search(pattern, result.stdout)
        if match:
            task_id = match.group()
            ask_cmd = f'volc ml_task get --id {task_id} --output json ' + \
                      '--format Status'
            log_cmd = f'volc ml_task logs --task {task_id} --instance worker_0'
            while True:
                task_status = os.popen(ask_cmd).read()
                pattern = r'(?<=\[{"Status":").*(?="}\])'
                match = re.search(pattern, task_status)
                if match:
                    task_status = match.group()
                else:
                    task_status = 'Exception'
                if self.debug:
                    print(task_status)
                logs = os.popen(log_cmd).read()
                with open(log_path, 'w', encoding='utf-8') as f:
                    f.write(logs)
                if task_status in [
                        'Success', 'Failed', 'Cancelled', 'Exception',
                        'Killing'
                ]:
                    break
                time.sleep(poll_interval)
        else:
            task_status = 'Exception'

        return task_status, result.returncode

    def _job_failed(self, task_status: str, output_paths: List[str]) -> bool:
        return task_status != 'Success' or not all(
            osp.exists(output_path) for output_path in output_paths)

    def _choose_flavor(self, num_gpus):
        config_path = self.volcano_cfg.volcano_config_path
        with open(config_path) as fp:
            volc_cfg = yaml.safe_load(fp)
        # TODO
        if not config_path.endswith('infer.yaml'):
            return volc_cfg
        if num_gpus <= 0 or num_gpus > 8:
            raise NotImplementedError
        if num_gpus == 1:
            flavor = 'ml.pni2l.3xlarge'
        elif num_gpus == 2:
            flavor = 'ml.pni2l.7xlarge'
        elif num_gpus <= 4:
            flavor = 'ml.pni2l.14xlarge'
        else:
            flavor = 'ml.hpcpni2l.28xlarge'
        role_specs = volc_cfg['TaskRoleSpecs']
        for i in range(len(role_specs)):
            if role_specs[i]['RoleName'] == 'worker':
                role_specs[i]['Flavor'] = flavor

        return volc_cfg
