from mmengine.config import read_base

with read_base():
    from ...summarizers.groups.mmlu import mmlu_summary_groups
    from ...summarizers.groups.ceval import ceval_summary_groups
    from ...summarizers.groups.bbh import bbh_summary_groups
    from ...summarizers.groups.ds1000 import ds1000_summary_groups

summarizer = dict(
    dataset_abbrs=[
        # '--------- 考试 Exam ---------',  # category
        # 'Mixed', # subcategory
        "ceval",
        'mmlu',
        # '--------- 语言 Language ---------',  # category
        # '成语习语', # subcategory
        'chid-dev',
        # '语义相似度', # subcategory
        'afqmc-dev',
        # '指代消解', # subcategory
        'winogrande',
        # '知识问答', # subcategory
        'BoolQ',
        'triviaqa',
        # '--------- 推理 Reasoning ---------',  # category
        # '文本蕴含', # subcategory
        'ocnli',
        # '常识推理', # subcategory
        'piqa',
        # '数学推理', # subcategory
        'math',
        'gsm8k',
        # '代码', # subcategory
        'openai_humaneval',
        'mbpp',
        # '综合推理', # subcategory
        "bbh",
        # '--------- 理解 Understanding ---------',  # category
        # '阅读理解', # subcategory
        'CMRC_dev',
        'DRCD_dev',
        # '内容总结', # subcategory
        'Xsum',
        # '--------- ceval 细节 ---------',
        "ceval-stem",
        "ceval-social-science",
        "ceval-humanities",
        "ceval-other",
        "ceval-hard",
        # category
        'ceval-advanced_mathematics',
        'ceval-college_chemistry',
        'ceval-college_physics',
        'ceval-college_programming',
        'ceval-computer_architecture',
        'ceval-computer_network',
        'ceval-discrete_mathematics',
        'ceval-electrical_engineer',
        'ceval-high_school_biology',
        'ceval-high_school_chemistry',
        'ceval-high_school_mathematics',
        'ceval-high_school_physics',
        'ceval-metrology_engineer',
        'ceval-middle_school_biology',
        'ceval-middle_school_chemistry',
        'ceval-middle_school_mathematics',
        'ceval-middle_school_physics',
        'ceval-operating_system',
        'ceval-probability_and_statistics',
        'ceval-veterinary_medicine',
        'ceval-business_administration',
        'ceval-college_economics',
        'ceval-education_science',
        'ceval-high_school_geography',
        'ceval-high_school_politics',
        'ceval-mao_zedong_thought',
        'ceval-marxism',
        'ceval-middle_school_geography',
        'ceval-middle_school_politics',
        'ceval-teacher_qualification',
        'ceval-art_studies',
        'ceval-chinese_language_and_literature',
        'ceval-high_school_chinese',
        'ceval-high_school_history',
        'ceval-ideological_and_moral_cultivation',
        'ceval-law',
        'ceval-legal_professional',
        'ceval-logic',
        'ceval-middle_school_history',
        'ceval-modern_chinese_history',
        'ceval-professional_tour_guide',
        'ceval-accountant',
        'ceval-basic_medicine',
        'ceval-civil_servant',
        'ceval-clinical_medicine',
        'ceval-environmental_impact_assessment_engineer',
        'ceval-fire_engineer',
        'ceval-physician',
        'ceval-plant_protection',
        'ceval-sports_science',
        'ceval-tax_accountant',
        'ceval-urban_and_rural_planner',
        # '--------- mmlu 细节 ---------',
        'mmlu-humanities',
        'mmlu-stem',
        'mmlu-social-science',
        'mmlu-other',
        # category
        'lukaemon_mmlu_abstract_algebra',
        'lukaemon_mmlu_anatomy',
        'lukaemon_mmlu_astronomy',
        'lukaemon_mmlu_business_ethics',
        'lukaemon_mmlu_clinical_knowledge',
        'lukaemon_mmlu_college_biology',
        'lukaemon_mmlu_college_chemistry',
        'lukaemon_mmlu_college_computer_science',
        'lukaemon_mmlu_college_mathematics',
        'lukaemon_mmlu_college_medicine',
        'lukaemon_mmlu_college_physics',
        'lukaemon_mmlu_computer_security',
        'lukaemon_mmlu_conceptual_physics',
        'lukaemon_mmlu_econometrics',
        'lukaemon_mmlu_electrical_engineering',
        'lukaemon_mmlu_elementary_mathematics',
        'lukaemon_mmlu_formal_logic',
        'lukaemon_mmlu_global_facts',
        'lukaemon_mmlu_high_school_biology',
        'lukaemon_mmlu_high_school_chemistry',
        'lukaemon_mmlu_high_school_computer_science',
        'lukaemon_mmlu_high_school_european_history',
        'lukaemon_mmlu_high_school_geography',
        'lukaemon_mmlu_high_school_government_and_politics',
        'lukaemon_mmlu_high_school_macroeconomics',
        'lukaemon_mmlu_high_school_mathematics',
        'lukaemon_mmlu_high_school_microeconomics',
        'lukaemon_mmlu_high_school_physics',
        'lukaemon_mmlu_high_school_psychology',
        'lukaemon_mmlu_high_school_statistics',
        'lukaemon_mmlu_high_school_us_history',
        'lukaemon_mmlu_high_school_world_history',
        'lukaemon_mmlu_human_aging',
        'lukaemon_mmlu_human_sexuality',
        'lukaemon_mmlu_international_law',
        'lukaemon_mmlu_jurisprudence',
        'lukaemon_mmlu_logical_fallacies',
        'lukaemon_mmlu_machine_learning',
        'lukaemon_mmlu_management',
        'lukaemon_mmlu_marketing',
        'lukaemon_mmlu_medical_genetics',
        'lukaemon_mmlu_miscellaneous',
        'lukaemon_mmlu_moral_disputes',
        'lukaemon_mmlu_moral_scenarios',
        'lukaemon_mmlu_nutrition',
        'lukaemon_mmlu_philosophy',
        'lukaemon_mmlu_prehistory',
        'lukaemon_mmlu_professional_accounting',
        'lukaemon_mmlu_professional_law',
        'lukaemon_mmlu_professional_medicine',
        'lukaemon_mmlu_professional_psychology',
        'lukaemon_mmlu_public_relations',
        'lukaemon_mmlu_security_studies',
        'lukaemon_mmlu_sociology',
        'lukaemon_mmlu_us_foreign_policy',
        'lukaemon_mmlu_virology',
        'lukaemon_mmlu_world_religions',
        'maxmin',
        'py150',
        'ds1000',
        'ds1000_Pandas', 
        'ds1000_Numpy', 
        'ds1000_Tensorflow', 
        'ds1000_Scipy', 
        'ds1000_Sklearn', 
        'ds1000_Pytorch', 
        'ds1000_Matplotlib'
    ],
    summary_groups=sum(
        [v for k, v in locals().items() if k.endswith("_summary_groups")], []),
    prompt_db=dict(
        database_path='configs/datasets/log.json',
        config_dir='configs/datasets',
        blacklist='.promptignore'),
)
