from mmengine.config import read_base

with read_base():
   from ..groups.mmlu import mmlu_summary_groups

summarizer = dict(
    dataset_abbrs = [
        # MMLU
        'lukaemon_mmlu_abstract_algebra',
        'lukaemon_mmlu_anatomy',
        'lukaemon_mmlu_astronomy',
        'lukaemon_mmlu_business_ethics',
        'lukaemon_mmlu_clinical_knowledge',
        'lukaemon_mmlu_college_biology',
        'lukaemon_mmlu_college_chemistry',
        'lukaemon_mmlu_college_computer_science',
        'lukaemon_mmlu_college_mathematics',
        'lukaemon_mmlu_college_medicine',
        'lukaemon_mmlu_college_physics',
        'lukaemon_mmlu_computer_security',
        'lukaemon_mmlu_conceptual_physics',
        'lukaemon_mmlu_econometrics',
        'lukaemon_mmlu_electrical_engineering',
        'lukaemon_mmlu_elementary_mathematics',
        'lukaemon_mmlu_formal_logic',
        'lukaemon_mmlu_global_facts',
        'lukaemon_mmlu_high_school_biology',
        'lukaemon_mmlu_high_school_chemistry',
        'lukaemon_mmlu_high_school_computer_science',
        'lukaemon_mmlu_high_school_european_history',
        'lukaemon_mmlu_high_school_geography',
        'lukaemon_mmlu_high_school_government_and_politics',
        'lukaemon_mmlu_high_school_macroeconomics',
        'lukaemon_mmlu_high_school_mathematics',
        'lukaemon_mmlu_high_school_microeconomics',
        'lukaemon_mmlu_high_school_physics',
        'lukaemon_mmlu_high_school_psychology',
        'lukaemon_mmlu_high_school_statistics',
        'lukaemon_mmlu_high_school_us_history',
        'lukaemon_mmlu_high_school_world_history',
        'lukaemon_mmlu_human_aging',
        'lukaemon_mmlu_human_sexuality',
        'lukaemon_mmlu_international_law',
        'lukaemon_mmlu_jurisprudence',
        'lukaemon_mmlu_logical_fallacies',
        'lukaemon_mmlu_machine_learning',
        'lukaemon_mmlu_management',
        'lukaemon_mmlu_marketing',
        'lukaemon_mmlu_medical_genetics',
        'lukaemon_mmlu_miscellaneous',
        'lukaemon_mmlu_moral_disputes',
        'lukaemon_mmlu_moral_scenarios',
        'lukaemon_mmlu_nutrition',
        'lukaemon_mmlu_philosophy',
        'lukaemon_mmlu_prehistory',
        'lukaemon_mmlu_professional_accounting',
        'lukaemon_mmlu_professional_law',
        'lukaemon_mmlu_professional_medicine',
        'lukaemon_mmlu_professional_psychology',
        'lukaemon_mmlu_public_relations',
        'lukaemon_mmlu_security_studies',
        'lukaemon_mmlu_sociology',
        'lukaemon_mmlu_us_foreign_policy',
        'lukaemon_mmlu_virology',
        'lukaemon_mmlu_world_religions',
        'mmlu-humanities',
        'mmlu-stem',
        'mmlu-social-science',
        'mmlu-other',
        'mmlu',
    ],
    summary_groups=mmlu_summary_groups,
    prompt_db=dict(
        database_path='configs/datasets/log.json',
        config_dir='configs/datasets',
        blacklist='.promptignore')
)
